### ISSUE TITLE
[BUG] - Age is NaN from some valid personnummer

### ISSUE THREAD

**Issue by spacecakes** [personnummer/js#206] opened 2021-03-18 21:09 UTC
Can't get age from some otherwise valid personnummer.

Steps to reproduce: 

1. Go to [the Personnummer website](https://personnummer.dev)
2. Try `199102040632`
3. Returned age is `NaN`

Affected browsers (that I know of): 
Safari, Safari on iOS

**Comment by frozzare** [comment] 2021-03-18 21:11
Can't reproduce, how do you get the `NaN` on age? 

<img width="771" alt="Screenshot 2021-03-18 at 22 11 02" src="https://user-images.githubusercontent.com/14610/111698208-da7a6d00-8836-11eb-93ef-22647904e178.png">

**Comment by spacecakes** [comment] 2021-03-18 21:17
Wow, that was fast! Upon further testing it seems to be browser specific.

Does not work in Safari 14.0.3 on macOS or iOS 14. _Does_ work in Chrome and Firefox though.

**Comment by spacecakes** [comment] 2021-03-18 21:17
Woops, accidentall

**Comment by frozzare** [comment] 2021-03-18 21:29
Thanks for report, will be fixed and new version is out soon.

**Comment by spacecakes** [comment] 2021-03-18 21:32
Thanks for the fix and quick response. Just noticed this on our prod this evening! Huge thanks

**Closed** 2021-03-18 21:34 UTC
Labels: bug
